### ISSUE TITLE
mdt is not compatible with recent versions of mongodb drivers (meteor 2.6.1)

### ISSUE THREAD

**Issue by antislash21** [MeXaaR/mdt#2]
When upgrading to meteor 2.6.1, this package fails with the following error :

```
W20220314-11:51:18.935(1)? (STDERR) (node:43488) UnhandledPromiseRejectionWarning: TypeError: collectionsData.each is not a function
W20220314-11:51:18.936(1)? (STDERR)     at packages/mexar:mdt/server/methods.js:12:19
W20220314-11:51:18.936(1)? (STDERR)     at /home/bruno/.meteor/packages/promise/.0.12.0.9s8dam.ac5dl++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20220314-11:51:18.936(1)? (STDERR) (Use `node --trace-warnings ...` to show where the warning was created)
W20220314-11:51:18.937(1)? (STDERR) (node:43488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
W20220314-11:51:18.937(1)? (STDERR) (node:43488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The following changes should fix this

in server/methods.js (startup code).

```
...
  const collectionsData = await db.listCollections().toArray();
  collectionsData.forEach((collection) => {
...

```

**Comment by MeXaaR** [comment]
fixed with 0.2.2
